spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/page_test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  #redis:
  #  password: 123456
  #  port: 6379
  #  host: 192.168.109.135
server:
  port: 8090

simple:
  pagination:
    enabled: true
    sqlDialect: mysql