spring:
  datasource:
    db:
      url: jdbc:mysql://127.0.0.1:3306/page_test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    postgresql:
      url: jdbc:postgresql://192.168.54.216:5432/postgres
      username: postgres
      password: xtpbxx
      driver-class-name: org.postgresql.Driver
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat
      max-open-prepared-statements: 10
      pool-prepared-statements: true
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)
      min-evictable-idle-time-millis: 300000
      test-on-return: true
      test-on-borrow: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      max-wait: 10000
      max-active: 20
      max-idle: 10
      min-idle: 5
      initial-size: 5
  #redis:
  #  password: 123456
  #  port: 6379
  #  host: 192.168.109.135
server:
    port: 8888


#simple:
#  pagination:
#    enabled: true
#    sqlDialect: MySQL
#    default-page: 1
#    default-size: 5
#    page-field: pageIndex
#    size-field: pageSize

mybatis-plus:
  type-aliases-package: com.simple.page
  mapper-locations: classpath*:mapper/*.xml
  # mybatis-plus 的全局配置
  global-config:
    banner: false
  # mybatis 原生配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false